global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5001']

  - job_name: 'doctor-service'
    static_configs:
      - targets: ['doctor-service:5002']

  - job_name: 'appointment-service'
    static_configs:
      - targets: ['appointment-service:5003']

